// Components/jokes.js
// По персонажам: 'wolf', 'pigA', 'pigB', 'pigC'

export const JOKES = {
    wolf: [
      "Why don’t I eat vegetarian food? Because lettuce never screams \"save me!\"",
      "I’m walking through the forest, I see a trail. I think: either it’s a deer, or I’ve lost my slipper again.",
      "Why don’t I have any friends? Because every time I say \"let’s eat something,\" everyone runs away.",
      "I tried to be nice. It worked. But it was tasteless.",
      "I was invited to go on a diet. I said: \"I’m already on it – I only eat those who run slowly.\"",
      "Everyone in the gym is afraid of me. Especially the treadmills.",
      "How do you know if a wolf is on a diet? He chews grass and cries.",
      "I decided to go vegan. Now I hunt for mushrooms.",
      "My neighbor says: \"Are you a wolf or a dog?\" I answer: \"It depends on who you ask – me or the postman.\"",
      "When I sing at night, they call me a romantic. When pigs – karaoke.",
      "Why don't I ever take a taxi? Because they always chase me for free.",
      "I was invited to the circus. They said: \"You're funny as it is.\"",
      "How does a wolf save money? He eats once - but a lot.",
      "I asked the doctor for an appetite suppressant. He gave me a mirror.",
      "I was always the favorite at school. Especially in the lesson \"Who's Afraid of the Wolf\".",
      "Why don't they ever let me into the pigsty? Because I'm like a sanitary inspector there.",
      "I like sports. Especially running. After pigs.",
      "How does a wolf propose? \"Wouldn't you like to be my dinner?\"",
      "I was at a wild boar's wedding. Now I think it was the menu.",
      "Why doesn't a wolf work in the office? Because they don't feed them there.",
      "My name is \"gray\". Have you seen my electricity bills? Black!",
      "I am a vegetarian... between meat snacks.",
      "They ask me: \"What do you like?\" - \"Those who don't like to run.\"",
      "Why don't I go to the movies? Because I want to eat popcorn all the time... with my neighbor.",
      "I started a blog. I called it \"100 Ways to Cook a Pig.\"",
      "I get offended when people call me a predator. I just like \"warm food.\"",
      "When I laugh, I make \"ha-ha.\" When pigs laugh, they make \"khrum-khrum.\"",
      "Why don't I play chess? Because all the pieces are wooden, and I like meat ones.",
      "I walked around the village - everyone closed the door. They think I'm scary. But I'm just hungry.",
      "I got a cat. Now at least someone in the house is not afraid.",
      "I was invited to a picnic. They said: \"Bring something tasty.\" I brought myself.",
      "I decided to lose weight. The boar lost weight.",
      "Why don't wolves go to restaurants? Because the check is longer than a pig.",
      "I train every morning: pull-ups, squats, chasing.",
      "A wolf at a party is like a cake without candles. It seems beautiful, but everyone is nervous.",
      "I decided to become a teacher. The first lesson: \"How to run away from me correctly.\"",
      "I tried reading a book. But pigs run faster than I read.",
      "The wolf's favorite sport is jumping over a fence.",
      "I played \"Mafia.\" And, surprisingly, I won right away.",
      "When I say, \"I want a snack,\" everyone starts running away. For some reason.",
      "I wanted to start a family. But all the candidates ran away.",
      "The wolf and the pigs opened a cafe. The slogan: \"Come while we're still together.\"",
      "Why don't I play the guitar? Because the strings don't taste good.",
      "I invited a pig to the movies. She says: \"You'll eat me!\" - \"Be quiet, we're not in a restaurant!\"",
      "They call me scary, but I just want to hug... tightly and for a long time.",
      "I tried the \"no dinner\" diet. Now my neighbor has dinner.",
      "I'm very modest. Especially after three pigs for dinner.",
      "A wolf in a store: \"Give me some meat.\" The seller: \"Which one?\" - \"Which one will run away.\"",
      "They called me to the football team. But I chase the ball like a pig all the time.",
      "I look in the mirror and think: \"Handsome!\" And everyone else - \"Predator!\"",
    ],
  
    // Pig 1 — foodie
    pigA: [
      "They say: \"Breakfast is the most important meal.\" That’s why I eat breakfast three times a day.",
      "My friends ask: \"Why do you always have a pie?\" – Because it never betrays me.",
      "I’m on a diet. Now I only eat when I’m hungry. That is, all the time.",
      "When I go into the kitchen, the refrigerator starts to cry.",
      "I love sports. Especially running… to the refrigerator.",
      "They told me: \"Count the calories!\" I said: \"One, two, three… delicious!\"",
      "I have willpower. But a pie is stronger.",
      "They say that money doesn’t bring happiness. But they buy pizza.",
      "The hardest thing in my life is waiting for the borscht to cool down.",
      "I can live without food. But not for long.",
      "My favorite sound is the “ding” of the microwave.",
      "When I lose weight, the buns lose weight with me. But not for long.",
      "They ask me: \"What do you do in your free time?\" – \"Room for dessert!\"",
      "At the gym, I only do one thing – I open the snack cabinet.",
      "I am an optimist: even in an empty plate I see a place for food.",
      "My neighbor asked: \"Why are you always chewing?\" – \"What can I do to not think?\"",
      "My hobby is collecting crumbs on my T-shirt.",
      "If I am silent – it means I am chewing.",
      "I try to save money. That is why I finish everything myself.",
      "They say: \"You are what you eat\". It turns out I am a cake.",
      "I love winter. Because there is hot mulled wine and dumplings.",
      "I tried fasting. I lasted until lunch.",
      "My stomach is my personal bank. Always full.",
      "If I am happy – I eat. If I am sad – I eat too.",
      "I can only be made to laugh with one word: \"kebab\".",
      "I want to go to the movies. But I’m afraid the popcorn will run out before the credits roll.",
      "I was invited to a party. I thought it was a buffet.",
      "A crunch without food is like a phone without a charger.",
      "The best exercise is chewing gum with jaw squats.",
      "I have a diet: sweet after salty.",
      "When someone invites me for a walk, I ask: \"Is there a cafe there?\"",
      "I could live without the Internet… but without borscht – never.",
      "I was given a vase. I thought it was a soup bowl.",
      "I’m learning foreign languages. The first word is \"pizza\".",
      "I love the theater. Especially the buffet in the theater.",
      "I have dreams where I finish the pizza. I wake up happy.",
      "I don’t argue with my friends. I bribe them with cookies.",
      "I always have a clean refrigerator. Because I clean it from the inside.",
      "I am a philosopher: life is short, and shawarma is long.",
      "They say: \"Don’t eat at night.\" And I prove the opposite every night.",
      "I don’t believe in miracles. I believe in food delivery.",
      "I want to be an astronaut. There are tubes of food there too.",
      "How do I know I’m happy? I have full cheeks.",
      "I signed up for cooking courses. Now my dishes disappear even faster.",
      "When I see a cake, I have two options: eat it or eat it faster.",
      "They say that you need to eat to live. But I live to eat.",
      "The best gift for me is an edible one.",
      "I can’t go on a diet. Because my stool is too hard for that.",
      "I like the smell of morning. Especially if it's the smell of fried potatoes.",
      "My dream is a refrigerator without doors. So that there is always access.",
    ],
  
    // Pig 2 — nerdy/smart
    pigB: [
      "They say: \"Knowledge is power.\" That’s why I’m stronger than dumbbells.",
      "I’m so smart that even a calculator asks me for advice.",
      "I was invited to a club. I thought it was a book club.",
      "How do you know I’m a genius? I laugh at my own jokes.",
      "My favorite subject at school is the cafeteria. I always get an A there.",
      "I love physics. Especially the law of gravity… to the refrigerator.",
      "They say: \"You’re too serious.\" And I say: \"That’s my scientific humor.\"",
      "I solved an equation. And it took it and ran away.",
      "They gave me a math textbook. And I autographed it.",
      "I’m a philosopher. Because even in porridge I see meaning.",
      "I can explain anything. Even why I ate three pies.",
      "They ask me: \"Why are you wearing glasses?\" – \"To see my mistakes better.\"",
      "I know three languages: Ukrainian, English, and the language of the cafe menu.",
      "How do I prepare for exams? I learn how to look smart.",
      "I was invited to a TV quiz show. I won. A cake.",
      "A smart person's favorite transport is thoughts. They are always free.",
      "I love chess. You can also eat a horse there.",
      "They say: \"Smart people don't have money.\" Then I'm definitely a millionaire in science.",
      "I don't copy. I check the correctness of other people's thoughts.",
      "There are two formulas in my life: F = ma and \"Fu, not enough food.\"",
      "I am always right. Even when I am wrong. Because logic has decided so.",
      "They say: \"A book is a man's friend.\" And my refrigerator is an even better friend.",
      "I read a book about a diet. And I snack on it.",
      "They are afraid of me in the library. Because I read my jokes out loud.",
      "I am a smart guy. But even I don’t understand why borscht is so delicious.",
      "I am looking for the truth. It must be at the bottom of the pot.",
      "I like astronomy. Because there are stars there, not just pigs.",
      "I decided to open a startup. I called it: \"Glasses for those who can’t see their lunch.\"",
      "I know all the capitals of the world. But the best is the capital with food.",
      "I was asked: \"What is your goal?\" – \"To finish this pizza.\"",
      "I love logic. But sometimes logic loves me too much.",
      "I am not accepted into the company. Because I explain a joke for a long time.",
      "I am preparing for the Olympics. Sports. After running to the cafeteria.",
      "They say I am smart. It’s just that I have a very thick book.",
      "I always have a plan. And it always starts with the word \"pie.\"",
      "I love geography. Because there you can find the country \"Dessert\".",
      "I never argue. I just prove that I am right.",
      "When I think, I eat. And when I eat, I think even more.",
      "My formula for happiness: IQ + BBQ.",
      "I wrote a book. I called it \"How to live deliciously and correctly\".",
      "I love science. Especially the science of cooking.",
      "People ask me: \"You are smart, why do you need food?\" – \"And why do you need intelligence without lunch?\"",
      "I can explain anything. Even why I have two desserts.",
      "My favorite laboratory is the kitchen. The experiments there are always delicious.",
      "I study history. I start with the history of cutlets.",
      "People ask me: \"Are you learning?\" – \"Yes, I am learning how to crunch properly\".",
      "I love mathematics. Especially multiplication... cutlets.",
      "I found a new planet. I called it \"Salo-Mars\".",
      "I always have the right answer: \"Food\".",
      "I can win any contest. Especially pancake eating.",
    ],
  
    // Pig 3 — hyperactive
    pigC: [
      "I don’t run — I fly low!",
      "They say: \"Sit still\". And I’m already on a tree.",
      "I have two states: \"jumping\" and \"jumping a lot\".",
      "I tried sitting still. I lasted three seconds.",
      "They don’t let me into the library. Because I run between the shelves there.",
      "In the gym I’m like a windmill. I’m spinning all the time.",
      "I don’t get tired. I just pause for a joke.",
      "They say I’m hyperactive. I say: \"What does that mean?\" and I keep jumping.",
      "I run so fast that the refrigerator can’t keep up with me.",
      "If I laugh, the whole room jumps.",
      "I want to become a dancer. Because I can already jump without music.",
      "I was invited to the circus. I said: \"I’m already the circus!\"",
      "I have wings… only invisible ones.",
      "I can jump over a fence. But then I go back for a bun.",
      "I don’t walk – I hop.",
      "They say: \"You’re too loud.\" And I say: \"That’s the sound of happiness.\"",
      "I like to have fun so much that even a wolf laughs.",
      "They gave me coffee. Now I can’t be seen.",
      "I’m always late. Because first I jump, then I walk.",
      "It’s hard to take pictures of me. Because I never stand still.",
      "I don’t dance. I just happen to move beautifully.",
      "I have a talent — I can fall and laugh at the same time.",
      "When I play football, the ball is afraid of me.",
      "They say: \"You’re crazy.\" I answer: \"No, I’m very cheerful.\"",
      "I sleep quickly. Because even in my dreams I’m in a hurry.",
      "My favorite sport is a laughter marathon.",
      "I can tell a joke and run away while you laugh.",
      "I'm so active that even flies get tired of me.",
      "I love to jump. Especially on the sofa — ten times in a row.",
      "They ask me: \"Aren't you tired?\" — \"I haven't even started yet!\"",
      "I'm a workout for all my friends. Sometimes I'm just too strong.",
      "I tried to sit still. But the chair broke from laughing.",
      "My name is Sandman. Because I jump even in the sand.",
      "I came up with a new sport — sprinting with laughter.",
      "I always make it to lunch. Because I run faster than the clock.",
      "I can fall into a puddle and make a show out of it.",
      "When I start joking, the neighbors think it's an earthquake.",
      "I like to talk fast. Because thoughts don't wait.",
      "I try to count to ten. But after three I jump.",
      "They ask me: \"Why do you laugh all the time?\" — \"Because it’s free.\"",
      "I play hide-and-seek with myself. And I always win.",
      "I have a secret. I don’t drink coffee. I breathe coffee.",
      "They say I’m like a battery. Only I don’t need to be charged.",
      "I can tell a hundred jokes in a minute. The main thing is to have time to laugh.",
      "I even jump in the elevator. Then the elevator cries.",
      "I have a dream: to run around the world, but stop for shawarma.",
      "I can laugh at a joke for another week.",
      "I can’t be quieted. You can only sing along.",
      "I came up with laughter gymnastics. Now I have cubes… of laughter.",
      "I’m like a holiday. I’m never quiet.",
    ],
  };
  
  // Утилиты (по желанию)
  export const getJokesFor = (key) => JOKES[key] || [];
  export const getJoke = (key, index = 0) =>
    (JOKES[key] && JOKES[key][index % JOKES[key].length]) || "";
  export default JOKES;
  